"""Add Horus Operations models

Revision ID: 4158a0819fe0
Revises: 9c29da8aaed1
Create Date: 2026-06-01 00:02:52.360689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4158a0819fe0'
down_revision: Union[str, Sequence[str], None] = '9c29da8aaed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v2_horus_approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v2_horus_approval_requests_campus_id'), 'v2_horus_approval_requests', ['campus_id'], unique=False)
    op.create_index(op.f('ix_v2_horus_approval_requests_status'), 'v2_horus_approval_requests', ['status'], unique=False)
    op.create_table('v2_horus_briefings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('summary_content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v2_horus_briefings_campus_id'), 'v2_horus_briefings', ['campus_id'], unique=False)
    op.create_index(op.f('ix_v2_horus_briefings_date'), 'v2_horus_briefings', ['date'], unique=False)
    op.create_table('v2_horus_workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_name', sa.String(length=255), nullable=False),
    sa.Column('trigger_event', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('conditions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v2_horus_workflows_enabled'), 'v2_horus_workflows', ['enabled'], unique=False)
    op.create_index(op.f('ix_v2_horus_workflows_trigger_event'), 'v2_horus_workflows', ['trigger_event'], unique=False)
    op.create_table('v2_mock_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('standard_id', sa.UUID(), nullable=False),
    sa.Column('simulation_status', sa.String(length=50), nullable=False),
    sa.Column('report_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v2_mock_audits_campus_id'), 'v2_mock_audits', ['campus_id'], unique=False)
    op.create_index(op.f('ix_v2_mock_audits_standard_id'), 'v2_mock_audits', ['standard_id'], unique=False)
    op.create_table('v2_horus_action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('triggering_event', sa.String(length=100), nullable=False),
    sa.Column('reasoning_summary', sa.String(), nullable=False),
    sa.Column('recommended_action', sa.String(length=100), nullable=False),
    sa.Column('executed_action', sa.String(length=100), nullable=False),
    sa.Column('action_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('policy_result', sa.String(length=50), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('execution_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['v2_horus_workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v2_horus_action_logs_campus_id'), 'v2_horus_action_logs', ['campus_id'], unique=False)
    op.create_index(op.f('ix_v2_horus_action_logs_correlation_id'), 'v2_horus_action_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_v2_horus_action_logs_created_at'), 'v2_horus_action_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_v2_horus_action_logs_workflow_id'), 'v2_horus_action_logs', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_v2_horus_action_logs_workflow_id'), table_name='v2_horus_action_logs')
    op.drop_index(op.f('ix_v2_horus_action_logs_created_at'), table_name='v2_horus_action_logs')
    op.drop_index(op.f('ix_v2_horus_action_logs_correlation_id'), table_name='v2_horus_action_logs')
    op.drop_index(op.f('ix_v2_horus_action_logs_campus_id'), table_name='v2_horus_action_logs')
    op.drop_table('v2_horus_action_logs')
    op.drop_index(op.f('ix_v2_mock_audits_standard_id'), table_name='v2_mock_audits')
    op.drop_index(op.f('ix_v2_mock_audits_campus_id'), table_name='v2_mock_audits')
    op.drop_table('v2_mock_audits')
    op.drop_index(op.f('ix_v2_horus_workflows_trigger_event'), table_name='v2_horus_workflows')
    op.drop_index(op.f('ix_v2_horus_workflows_enabled'), table_name='v2_horus_workflows')
    op.drop_table('v2_horus_workflows')
    op.drop_index(op.f('ix_v2_horus_briefings_date'), table_name='v2_horus_briefings')
    op.drop_index(op.f('ix_v2_horus_briefings_campus_id'), table_name='v2_horus_briefings')
    op.drop_table('v2_horus_briefings')
    op.drop_index(op.f('ix_v2_horus_approval_requests_status'), table_name='v2_horus_approval_requests')
    op.drop_index(op.f('ix_v2_horus_approval_requests_campus_id'), table_name='v2_horus_approval_requests')
    op.drop_table('v2_horus_approval_requests')
    # ### end Alembic commands ###
