"""add_operational_hardening_tables

Revision ID: 9c29da8aaed1
Revises: db42dd094040
Create Date: 2026-05-31 22:25:49.621399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c29da8aaed1'
down_revision: Union[str, Sequence[str], None] = 'db42dd094040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum type first in PostgreSQL
    failed_event_classification_enum = postgresql.ENUM('TRANSIENT', 'PERMANENT', 'VALIDATION', 'EXTERNAL_PROVIDER', 'TIMEOUT', 'RATE_LIMIT', name='v2_failed_event_classification_enum')
    failed_event_classification_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v2_ai_signal_logs_archive',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('compressed_prompt', sa.LargeBinary(), nullable=False),
    sa.Column('compressed_raw_response', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v2_ai_signal_logs_archive_correlation_id'), 'v2_ai_signal_logs_archive', ['correlation_id'], unique=False)
    op.create_table('v2_ai_usage_aggregates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('campus_id', sa.UUID(), nullable=True),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['v2_campuses.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['v2_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v2_ai_usage_aggregates_campus_id'), 'v2_ai_usage_aggregates', ['campus_id'], unique=False)
    op.create_index(op.f('ix_v2_ai_usage_aggregates_date'), 'v2_ai_usage_aggregates', ['date'], unique=False)
    op.create_index(op.f('ix_v2_ai_usage_aggregates_organization_id'), 'v2_ai_usage_aggregates', ['organization_id'], unique=False)
    op.create_table('v2_daily_readiness_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('standard_id', sa.UUID(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['v2_campuses.id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['v2_standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v2_daily_readiness_snapshots_campus_id'), 'v2_daily_readiness_snapshots', ['campus_id'], unique=False)
    op.create_index(op.f('ix_v2_daily_readiness_snapshots_date'), 'v2_daily_readiness_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_v2_daily_readiness_snapshots_standard_id'), 'v2_daily_readiness_snapshots', ['standard_id'], unique=False)
    op.add_column('v2_failed_events', sa.Column('classification', sa.Enum('TRANSIENT', 'PERMANENT', 'VALIDATION', 'EXTERNAL_PROVIDER', 'TIMEOUT', 'RATE_LIMIT', name='v2_failed_event_classification_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('v2_failed_events', 'classification')
    op.drop_index(op.f('ix_v2_daily_readiness_snapshots_standard_id'), table_name='v2_daily_readiness_snapshots')
    op.drop_index(op.f('ix_v2_daily_readiness_snapshots_date'), table_name='v2_daily_readiness_snapshots')
    op.drop_index(op.f('ix_v2_daily_readiness_snapshots_campus_id'), table_name='v2_daily_readiness_snapshots')
    op.drop_table('v2_daily_readiness_snapshots')
    op.drop_index(op.f('ix_v2_ai_usage_aggregates_organization_id'), table_name='v2_ai_usage_aggregates')
    op.drop_index(op.f('ix_v2_ai_usage_aggregates_date'), table_name='v2_ai_usage_aggregates')
    op.drop_index(op.f('ix_v2_ai_usage_aggregates_campus_id'), table_name='v2_ai_usage_aggregates')
    op.drop_table('v2_ai_usage_aggregates')
    op.drop_index(op.f('ix_v2_ai_signal_logs_archive_correlation_id'), table_name='v2_ai_signal_logs_archive')
    op.drop_table('v2_ai_signal_logs_archive')
    # ### end Alembic commands ###

    # Drop enum type in PostgreSQL
    failed_event_classification_enum = postgresql.ENUM('TRANSIENT', 'PERMANENT', 'VALIDATION', 'EXTERNAL_PROVIDER', 'TIMEOUT', 'RATE_LIMIT', name='v2_failed_event_classification_enum')
    failed_event_classification_enum.drop(op.get_bind(), checkfirst=True)
