"""Add V2 compliance pipeline models

Revision ID: db42dd094040
Revises: 9d31af90c575
Create Date: 2026-05-31 22:11:16.734687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from v2.core.database import PGVector

# revision identifiers, used by Alembic.
revision: str = 'db42dd094040'
down_revision: Union[str, Sequence[str], None] = '9d31af90c575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v2_ai_signal_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('raw_response', sa.String(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v2_ai_signal_logs_correlation_id'), 'v2_ai_signal_logs', ['correlation_id'], unique=False)
    op.create_table('v2_failed_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('worker_name', sa.String(length=100), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('exception', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v2_failed_events_correlation_id'), 'v2_failed_events', ['correlation_id'], unique=False)
    op.create_table('v2_standards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v2_criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('standard_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['v2_standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v2_notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'WEBHOOK', name='v2_notification_channel_enum'), nullable=False),
    sa.Column('min_severity', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['v2_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v2_campus_standards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('standard_id', sa.UUID(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['v2_campuses.id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['v2_standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v2_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'EXTRACTED', 'ANALYZED', 'VALIDATED', 'FAILED', name='v2_evidence_status_enum'), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['v2_campuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v2_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('campus_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', name='v2_notification_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['v2_campuses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['v2_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v2_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criterion_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('rule_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['v2_criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v2_risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='v2_risk_severity_enum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='v2_risk_status_enum'), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['v2_campuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v2_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'VERIFIED', name='v2_task_status_enum'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='v2_task_priority_enum'), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['v2_users.id'], ),
    sa.ForeignKeyConstraint(['campus_id'], ['v2_campuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v2_campus_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_ASSESSED', 'PARTIALLY_COVERED', 'COVERED', 'FULLY_COVERED', name='v2_requirement_status_enum'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['v2_campuses.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['v2_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v2_evidence_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['v2_evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v2_evidence_validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explainability_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['v2_evidence.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['v2_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('v2_evidence_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('embedding', PGVector(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['v2_evidence_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('v2_evidence_embeddings')
    op.drop_table('v2_evidence_validations')
    op.drop_table('v2_evidence_chunks')
    op.drop_table('v2_campus_requirements')
    op.drop_table('v2_tasks')
    op.drop_table('v2_risks')
    op.drop_table('v2_requirements')
    op.drop_table('v2_notifications')
    op.drop_table('v2_evidence')
    op.drop_table('v2_campus_standards')
    op.drop_table('v2_notification_preferences')
    op.drop_table('v2_criteria')
    op.drop_table('v2_standards')
    op.drop_index(op.f('ix_v2_failed_events_correlation_id'), table_name='v2_failed_events')
    op.drop_table('v2_failed_events')
    op.drop_index(op.f('ix_v2_ai_signal_logs_correlation_id'), table_name='v2_ai_signal_logs')
    op.drop_table('v2_ai_signal_logs')
    # ### end Alembic commands ###
